name: Multi job pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build steps
        run: check "building application..."

  test:
     runs-on: ubuntu-latest
   steps:
     - name: test step
       run:   echo "running test...."
  deploy:
     runs-on: ubuntu-latest
  steps:
     -name: deploy steps
      run: echo "Deploying application"
